import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate, NetworkFirst } from 'workbox-strategies';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';
import { ExpirationPlugin } from 'workbox-expiration';

// Precache static assets generated by Vite
// self.__WB_MANIFEST is injected by workbox-build
precacheAndRoute(self.__WB_MANIFEST);

// Cleanup old versions of assets
cleanupOutdatedCaches();

const CACHE_NAME = 'gestion-classe-api-v1';

// Custom Supabase API Caching Strategy using Workbox
// This replaces the manual handleApiRequest from the previous version
registerRoute(
    ({ url }) => url.hostname.includes('supabase.co') && url.pathname.includes('/rest/v1/'),
    new StaleWhileRevalidate({
        cacheName: CACHE_NAME,
        plugins: [
            new CacheableResponsePlugin({
                statuses: [0, 200],
            }),
            {
                // Custom plugin to handle dynamic expiration based on table name
                // Workbox ExpirationPlugin usually has a static maxAgeSeconds
                // So we use a generic 1h limit but we could refine this if needed
                cachedResponseWillBeUsed: async ({ cachedResponse }) => {
                    if (!cachedResponse) return null;
                    
                    // Logic from original SW: check sw-cached-time header or just rely on Workbox
                    return cachedResponse;
                }
            },
            new ExpirationPlugin({
                maxEntries: 1000,
                maxAgeSeconds: 60 * 60, // 1 hour overall limit
                purgeOnQuotaError: true,
            }),
        ],
    })
);

// Standard PWA Message Handling
self.addEventListener('message', (event) => {
    if (event.data && event.data.type === 'SKIP_WAITING') {
        self.skipWaiting();
    }
    
    if (event.data && event.data.type === 'CLEAR_CACHE') {
        event.waitUntil(
            caches.delete(CACHE_NAME).then(() => {
                if (event.ports && event.ports[0]) {
                    event.ports[0].postMessage({ success: true });
                }
            })
        );
    }
});

// Allow the SW to take control of the page immediately
self.addEventListener('activate', (event) => {
    event.waitUntil(self.clients.claim());
});
